### ISSUE TITLE
EDJE_CC Critical Error

### ISSUE THREAD

**Issue by webmaster-exit-1** [sylveon/terminology-themes#15] opened 2022-02-14 13:58 UTC
# Same error, over n over n over...

```console
edje_cc: Critical. Unable to load image "tab_shad_l0.png" used by file "themes/Zenburn.edj": File (or file path) does not exist. Check if path to file "tab_shad_l0.png" is correct (both directory and file name).
make: *** [Makefile:24: themes/Zenburn.edj] Error 255
make: Target 'install' not remade because of errors.
```

Even if I try to `make all -k -i` it fails. I even went as far as to `touch` the "missing" files. (sigh) I had a similar issue with the pika theme but was able to finagle my way into it installing. 
I'm using Arco (Arch) GNU/Linux 5.16.9-AMD x86_64

# **UPDATE!** While writing this!

Since I already have the missing files (tab_shad_*.png) in the pikalogy/images/ directory from the pikology build, I copied them over and got it done; with warnings. But at least no errors.

The Warnings: (for every theme)
* Warning: Image 'tab_shad_l0.png' not used
* Warning: Image 'tab_shad_l1.png' not used
* Warning: Image 'tab_shad_r0.png' not used
* Warning: Image 'tab_shad_r1.png' not used

I hope this comes in handy. It's a cool terminal with more potential under the hood just waiting for a developer to trick it out. It would be fun getting a bunch of people together and maybe pick out a favorite cartoon character to sprite-ify into the terminal. No. That would epic. (My mind is already thinking 'DarkWing Duck' lol) Take care :v: 
# And Thank you for the themes. <3

**Comment by andypiper** [comment] 2022-06-13 23:00
Yes, I'm seeing the same thing on a fresh checkout/build on Ubuntu. Per [this comment](https://github.com/sylveon/terminology-themes/issues/14#issuecomment-1000966705) it looks like this repo is no longer maintained.

**Comment by andypiper** [comment] 2022-06-13 23:03
This is also a duplicate of #11 - probably best if this repo is archived?

**Closed as completed** 2023-10-11 08:10 UTC
